#ifndef TESTVECTOR_MULTI_H
#define TESTVECTOR_MULTI_H

#include <stdint.h>

#define NUM_TEST_VECTORS 100
// Generated by generate_multi_vectors.py
// Starting Seed: 2025.1

// Declare that these variables exist in another object file
extern uint32_t message[100][32];
extern uint32_t K_X[100][32];
extern uint32_t K_Y[100][32];
extern uint32_t K_Z[100][32];
extern uint32_t s[100][32];
extern uint32_t Public_X[100][32];
extern uint32_t Public_Y[100][32];
extern uint32_t Public_Z[100][32];
extern uint32_t K_X_Modn[100][32];

// Start Point G 
extern uint32_t G_X[32];
extern uint32_t G_Y[32];
extern uint32_t G_Z[32];

#endif // TESTVECTOR_MULTI_H
